from django.urls import path
from recruitment.views import *

urlpatterns = [
    path("overview/", recruitment_overview, name="recruitment_overview"),
    path("hiringreq/", hiring_request_list, name="hiring_request"),
    path("hiringreq/<int:pk>/", hiring_request_detail,
         name="hiring_request_detail"),
    path("hiringreq/<int:pk>/status/",
         hiring_request_hr_action, name="hiring_request_staus"),

    path("public/jobs/", public_job_list, name="public_job_list"),
    path("public/jobs/<int:job_id>/", public_job_detail, name="public_job_detail"),
    path("public/jobs/<int:job_id>/apply/",
         public_job_apply, name="public_job_apply"),

    path("job-postings/", job_posting_list_create,
         name="job-posting-list-create"),
    path("job-postings/<int:pk>/",
         job_posting_detail, name="job-posting-detail"),
    path("job-postings/<int:pk>/applications/",
         job_posting_applications, name="job-posting-applications"),
    path("job-postings/<int:pk>/applications/<int:application_id>/",
         job_posting_application_detail, name="job-posting-application-detail"),
    path("job-postings/<int:pk>/status/",
         job_posting_status_change, name="job-posting-status-change"),

    path("applications/<int:application_id>/score/",
         run_cv_scoring_detail, name="run_cv_scoring_view"),
    path("jobs/<int:job_id>/rescore/",
         rescore_job_applications_bulk, name="rescore_job_applications_bulk"),
    path("jobs/<int:job_id>/pipeline/",
         candidate_pipeline_list_view, name="candidate_pipeline_list_view"),
    path("jobs/<int:job_id>/pipeline/",
         candidate_pipeline_list, name="candidate_pipeline_list"),
    path("applications/<int:application_id>/stage/",
         update_application_stage_view, name="update_application_stage_view"),
    path("applications/<int:application_id>/stage/",
         update_candidate_stage, name="update_candidate_stage"),
    path("applications/<int:application_id>/notes/",
         add_candidate_note_view, name="add_candidate_note_view"),
    path("applications/<int:application_id>/notes/",
         add_candidate_note, name="add_candidate_note"),
    path("applications/<int:application_id>/cv/",
         application_cv_download, name="application_cv_download"),
    path("applications/<int:application_id>/cv/",
         candidate_cv_download, name="candidate_cv_download"),
    path("applications/bulk-stage-update/",
         bulk_update_stage_view, name="bulk_update_stage_view"),
    path("applications/bulk-stage-update/",
         bulk_update_candidate_stage, name="bulk_update_candidate_stage"),

    path("email-templates/", email_template_list_create_view,
         name="email_template_list_create_view"),
    path("email-templates/", email_template_list_create,
         name="email_template_list_create"),
    path("email-templates/<int:pk>/",
         email_template_detail_view, name="email_template_detail_view"),
    path("email-templates/<int:pk>/",
         email_template_detail, name="email_template_detail"),
    path("email-preview/", preview_candidate_email_view,
         name="preview_candidate_email_view"),
    path("email-preview/", preview_candidate_email,
         name="preview_candidate_email"),
    path("email-send/", send_candidate_email_view,
         name="send_candidate_email_view"),
    path("email-send/", send_candidate_email,
         name="send_candidate_email"),
    path("email-retry-failed/", retry_failed_email_view,
         name="retry_failed_email_view"),
    path("email-retry-failed/", retry_failed_candidate_email,
         name="retry_failed_candidate_email"),
]
