# Generated by Django 5.2.17 on 2026-09-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('EXP_LET', 'Experience Letter'), ('APT_LET', 'Appointment Letter'), ('ITC', 'Income Tax Certificate'), ('NOC', 'NOC File'), ('SC', 'Salary Certificate')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('turnaround_days', models.PositiveIntegerField(default=3, help_text='Expected SLA in business days to fulfill this request.')),
                ('is_active', models.BooleanField(default=True, help_text='If False, employees cannot select this type when making new requests.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body_content', models.TextField(help_text='HTML or Plain text template. Use placeholders like {{employee_name}}, {{designation}}, {{monthly_salary}}, {{joining_date}}.')),
                ('include_letterhead', models.BooleanField(default=True)),
                ('letterhead_image', models.ImageField(blank=True, null=True, upload_to='letterheads/')),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='documents.documenttypeconfig')),
            ],
        ),
    ]
