# Generated by Django 5.2.17 on 2026-09-23 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(max_length=2500)),
                ('needed_by', models.DateField()),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('IN_PROGRESS', 'in progress'), ('READY', 'ready'), ('DELIVERED', 'delivered'), ('REJECTED', 'rejected'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=250)),
                ('rejection_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='generated_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_document_requests', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_request', to='documents.documenttypeconfig')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
