# Generated by Django 5.2.17 on 2026-09-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='file_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='manual_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Persistent unique reference number for the issued document.', max_length=80, null=True, unique=True),
        ),
    ]
