# Generated by Django 5.2.17 on 2026-09-25 07:55

import django.db.models.deletion
import policies.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(max_length=20000)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=policies.models.policy_upload_to)),
                ('version', models.FloatField(default=1.0)),
                ('is_madnatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='policies.policycategory')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyAckowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowleged_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='policies.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_acknowledgement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'policy')},
            },
        ),
    ]
