# Generated by Django 5.2.17 on 2026-09-25 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_rename_is_madnatory_policy_is_mandatory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='policyacknowledgement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='policy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='policyacknowledgement',
            name='policy_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='policyacknowledgement',
            unique_together={('user', 'policy', 'policy_version')},
        ),
        migrations.CreateModel(
            name='PolicyVersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('change_note', models.TextField(blank=True, default='')),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='policies.policy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
