# Generated by Django 5.2.17 on 2026-09-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_candidateemaillog_recipient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('REJECTION', 'Rejection'), ('SHORTLISTED', 'Shortlisted'), ('TEST_INVITATION', 'Test Invitation'), ('INTERVIEW_INVITATION', 'Interview Invitation'), ('OFFER', 'Offer'), ('HIRED', 'Hired'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=30),
        ),
    ]
